#!/bin/bash
set -euo pipefail
CURRENT_DIR=$(dirname "$0")
ROOT_DIR="$(realpath $(dirname "$0")/..)"

$CURRENT_DIR/build_docker

ICLOUDDS_VERSION="$(cat "$ROOT_DIR/setup.py" | grep version= | cut -d'"' -f 2)"
echo "Pushing Docker images for icloudds version: ${ICLOUDDS_VERSION}"

set +x
# The :latest tag is counterintuitive - It is only updated when pushing
# an untagged image, and it is not updated automatically when we push
# a versioned tag. We need to push twice to update both tags.
docker push "icloudds/icloudds:${ICLOUDDS_VERSION}"
docker push "icloudds/icloudds:${ICLOUDDS_VERSION}-alpine"
docker push "icloudds/icloudds:latest"
